// Code generated by glox-gen. DO NOT EDIT.

package main

type Expr interface {
	Accept(ExprVisitor) any
}

type ExprVisitor interface {
	VisitBinaryExpr(Expr) any
	VisitGroupingExpr(Expr) any
	VisitLiteralExpr(Expr) any
	VisitUnaryExpr(Expr) any
	VisitVariableExpr(Expr) any
	VisitAssignExpr(Expr) any
	VisitLogicalExpr(Expr) any
	VisitCallExpr(Expr) any
	VisitGetExpr(Expr) any
	VisitSetExpr(Expr) any
	VisitThisExpr(Expr) any
}

type Binary struct {
	left     Expr
	operator *Token
	right    Expr
}

func (e *Binary) Accept(v ExprVisitor) (ret any) {
	return v.VisitBinaryExpr(e)
}

type Grouping struct {
	expression Expr
}

func (e *Grouping) Accept(v ExprVisitor) (ret any) {
	return v.VisitGroupingExpr(e)
}

type Literal struct {
	value any
}

func (e *Literal) Accept(v ExprVisitor) (ret any) {
	return v.VisitLiteralExpr(e)
}

type Unary struct {
	operator *Token
	right    Expr
}

func (e *Unary) Accept(v ExprVisitor) (ret any) {
	return v.VisitUnaryExpr(e)
}

type Variable struct {
	name *Token
}

func (e *Variable) Accept(v ExprVisitor) (ret any) {
	return v.VisitVariableExpr(e)
}

type Assign struct {
	name  *Token
	value Expr
}

func (e *Assign) Accept(v ExprVisitor) (ret any) {
	return v.VisitAssignExpr(e)
}

type Logical struct {
	left     Expr
	operator *Token
	right    Expr
}

func (e *Logical) Accept(v ExprVisitor) (ret any) {
	return v.VisitLogicalExpr(e)
}

type Call struct {
	callee    Expr
	paren     *Token
	arguments []Expr
}

func (e *Call) Accept(v ExprVisitor) (ret any) {
	return v.VisitCallExpr(e)
}

type Get struct {
	object Expr
	name   *Token
}

func (e *Get) Accept(v ExprVisitor) (ret any) {
	return v.VisitGetExpr(e)
}

type Set struct {
	object Expr
	name   *Token
	value  Expr
}

func (e *Set) Accept(v ExprVisitor) (ret any) {
	return v.VisitSetExpr(e)
}

type This struct {
	keyword *Token
}

func (e *This) Accept(v ExprVisitor) (ret any) {
	return v.VisitThisExpr(e)
}
